version: "3.9"
services:
  login-service:
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    image: $CI_REGISTRY_IMAGE:prod-latest
    container_name: login-service
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      iteungwebnet:
        ipv4_address: 172.18.0.146

networks:
  iteungwebnet:
    external:
      name: iteungwebnet
